### ISSUE TITLE
Unable to load the requested file: includes/header.php

### ISSUE THREAD

**Issue by vimkaf** [trimmytech/paystack-codeigniter#2]
There is a missing view file that is loaded from the Guest Controller 
`$this->load->view('includes/header', $data);
 $this->load->view('includes/footer');`
and you never really explained how to run your code

**Comment by amish3** [comment]
Replace $this->load->view('includes/header', $data); with $this->load->view('header', $data);
(Reason: view function directly takes you to view folder which is present inside application. And when you use 'includes/header', this means that you are searching for includes folder inside view folder and I think in your project directory, there is no folder of the name "includes" inside view folder).
